export const profile = {
  email: "email@email.com",
  password: "ChangeMe123!",
  fullName: "Hire Me Jr",
  firstName: "Hire",
  lastName: "Me",
  suffix: "Jr",
  street: "1600 Amphitheatre Parkway",
  city: "Mountain View",
  state: "California",
  country: "United States",
  postalCode: "94043",
  phoneType: "Mobile",
  phoneNumber: "(650)-253-0000",
  school: "Meta University",
  degree: "Bachelors",
  fieldOfStudy: "Computer Science",
  gpa: "3.75",
  skills: ["Python", "SQL", "JavaScript", "React", "Node.js"],
  educationStartYear: "2022",
  educationEndYear: "2026",
  resumeFilePath: "./resume.pdf",
  linkedInLink: "https://www.linkedin.com/in/username/",
  githubLink: "https://github.com/username",
  portfolioLink: "",
  workAuthorization: "Yes",
  sponsorshipRequired: "No",
  gender: "Male",
  ethnicity: "Black",
  hispanicOrLatino: "No",
  veteranStatus: "I am not a veteran",
  disability: "no",
  autoSubmit: false,
  workexperiences: [
    {
      jobtitle: "Software Engineer",
      company: "Acme Metals LLC",
      location: "New York, New York",
      startDateMonth: "05",
      startDateYear: "2020",
      endDateMonth: "06",
      endDateYear: "2024",
      description: "Built and maintained internal software tools, collaborated with engineering teams, improved application reliability, and supported production workflows."
    }
  ]
};
